In [1]:
import pandas as pd
import time
import tweepy
import numpy as np
import re

In [2]:
def twitter_config():
    """
    Fungsi utilitas untuk mengkonfigurasi konsumsi file API Twitter dengan‚ê£
    ,!kunci yang disediakan.
    """
    # Otentikasi dan akses menggunakan kunci:
    auth = tweepy.OAuthHandler("JLGvLiMHnOZkSDyfvmNZOwB7j","crxgjo1KIRh0HAWZNec1vKO7MlAdc1MX7XzGGgVgBA6Mt30GrB")
    auth.set_access_token("1572483046141751298-Q3ZqiGCrM8zcGcw0fepHL1luRLXXr6","A0mYVIrOVVc2KHDdol3hsGS0LFFXiRPfxToGk7FIBWt97")
    # Kembalikan akses ke API:
    api = tweepy.API(auth)
    try:
        api.verify_credentials()
        print("Authentication OK")
    except:
        print("Error during authentication")
    return api

In [3]:
# buat extractor object
extractor = twitter_config()

Authentication OK

In [4]:
#Step 3 - Retrieve Tweets
tweets = extractor.search_tweets(q='TV digital stb', count=1000)
print("Tweets terambil: {}.\n".format(len(tweets)))

Tweets terambil: 100.

In [5]:
dataset_search = pd.DataFrame(data=[tweet.text for tweet in tweets], columns=['Tweets'])

# Kami membuat tampilan kerangka data:
display(dataset_search.head(16))

                                               Tweets
0   @hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...
1   @jokowi kesannya rakyat kecil jadi dipaksa bel...
2   @jokowi Semenjak dialihkannya TV analog ke TV ...
3   @jokowi Harga STB makin hari makin mahal, seda...
4   @jokowi Kenapa TV analog dialihkan ke TV digit...
5   @jokowi Semenjak dialihkannya TV analog ke TV ...
6   @jokowi Semenjak dialihkannya TV analog ke TV ...
7   @jokowi sebenarnya siapa yang diuntungkan deng...
8   @jokowi semoga dengan adanya peralihan saluran...
9   @jokowi semoga dengan adanya peralihan saluran...
10  Beli Tanaka Set top box dvb T2 HD tanaka stb T...
11  RT @brand_thread: Kominfo memberikan sertifika...
12  STB Gratis! Cukup Whatsapp Nomor ini, Set Top ...
13  RT @arifin34533: Khusus untuk yang nyinyir soa...
14  Khusus untuk yang nyinyir soal TV Digital...\n...
15  Temukan EARISE [ READY STOK ] Stb DVB-T2 / Set...

In [6]:
#Step 3 - Retrieve Tweets
tweets2 = extractor.search_tweets(q='harga STB', count=1000)
print("Tweets terambil: {}.\n".format(len(tweets2)))

Tweets terambil: 100.

In [7]:
dataset_search2 = pd.DataFrame(data=[tweet.text for tweet in tweets2], columns=['Tweets'])

# Kami membuat tampilan kerangka data:
display(dataset_search2.head(16))

                                               Tweets
0   @jokowi ga semua rakyat mampu membeli stb deng...
1   @jokowi Udah harga BBM naik, harga sembako jug...
2   @jokowi Harga STB makin hari makin mahal, seda...
3   @jokowi Sudah harga BBM naik, harga kebutuhan ...
4   @jokowi Harga STB mahal banget pak, belum sang...
5   @jokowi Sudah semua harga kebutuhan naik, semu...
6   @jokowi Pak tolong solusinya dong utk harga st...
7     @jokowi Maaf pak harga stb gmn, gada solusi ya?
8   @jokowi Gimana yah harga stb naik terus, gada ...
9        @jokowi Pak ko harga STB ini malah banget ya
10  @jokowi tidak meminta lebih tapi cukup berikan...
11  @jokowi karena harga stb ga murah, jelas beber...
12  @jokowi Harga STB kenapa bisa semahal ini Pak?...
13  @jokowi semoga aja cepet ada tindaklanjut soal...
14  @jokowi Untuk Harga STB ini kobisa semahal ini...
15  @jokowi Harga STB mahal di keadaan ekonomi yg ...

In [8]:
dataset_search_gb1 = dataset_search2.append(dataset_search)

In [9]:
dataset_search_gb1

                                               Tweets
0   @jokowi ga semua rakyat mampu membeli stb deng...
1   @jokowi Udah harga BBM naik, harga sembako jug...
2   @jokowi Harga STB makin hari makin mahal, seda...
3   @jokowi Sudah harga BBM naik, harga kebutuhan ...
4   @jokowi Harga STB mahal banget pak, belum sang...
..                                                ...
95  RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...
96  RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...
97  Hallo pemirsa setia tvOne! \nSegera lakukan sc...
98  Setelah pemerintah menghentikan siaran TV anal...
99  RT @detikinet: #Terpopuler Kementerian Komunik...

[200 rows x 1 columns]

In [10]:
#Step 3 - Retrieve Tweets
tweets3 = extractor.search_tweets(q='set top box TV Digital', count=1000)
print("Tweets terambil: {}.\n".format(len(tweets3)))

Tweets terambil: 96.

In [11]:
dataset_search3 = pd.DataFrame(data=[tweet.text for tweet in tweets3], columns=['Tweets'])

# Kami membuat tampilan kerangka data:
display(dataset_search3.head(16))

                                               Tweets
0   Membeli set top box atau TV digital  https://t...
1   Beli Nijoo&amp;Digital Set Top Box TV Digital ...
2   Digital Converter Box, Leelbox S3 ATSC Convert...
3   Beli Tanaka Set top box dvb T2 HD tanaka stb T...
4   Mulai 20 Desember 2022, siaran TV analog di wi...
5   RT @brand_thread: Kominfo memberikan sertifika...
6   RT @DS_yantie: Menkominfo @PlateJohnny mengata...
7   STB Gratis! Cukup Whatsapp Nomor ini, Set Top ...
8   RT @DS_yantie: Menkominfo @PlateJohnny mengata...
9   Beli Set Top Box atau alat penerima siaran TV ...
10  Klo pake tv digital gausah pke set top box lagi??
11  Membeli set top box atau TV digital untuk meno...
12  RT @DS_yantie: Menkominfo @PlateJohnny mengata...
13  Menkominfo @PlateJohnny mengatakan salah satu ...
14  Beda Set Top Box TV Digital Abal-abal dan Resm...
15  Daftar Set Top Box Resmi, TV Analog di Surabay...

In [12]:
dataset_search_gb2 = dataset_search3.append(dataset_search_gb1)

In [13]:
#Step 3 - Retrieve Tweets
tweets4 = extractor.search_tweets(q='siaran TV Digital', count=1000)
print("Tweets terambil: {}.\n".format(len(tweets4)))

Tweets terambil: 100.

In [14]:
dataset_search4 = pd.DataFrame(data=[tweet.text for tweet in tweets4], columns=['Tweets'])

# Kami membuat tampilan kerangka data:
display(dataset_search4.head(16))

                                               Tweets
0   Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...
1   @hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...
2   Lembaga penyiaran bersepakat melaksanakan peng...
3   RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...
4   Per tanggal 20 Desember 2022 pada pukul 24.00 ...
5   RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...
6   @hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...
7   Lembaga penyiaran bersepakat melaksanakan peng...
8   RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...
9   Per tanggal 20 Desember 2022 pada pukul 24.00 ...
10  Tv analog dimatikan, tv sinyal digital tidak m...
11  Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...
12  Beli Nijoo&amp;Digital Set Top Box TV Digital ...
13  Adapun, untuk bisa menonton TV Digital seiring...
14  Suntik Mati TV Analog Jatim Hari Ini, Begini C...
15  Hari Ini TV Analog Dimatikan di 10 Wilayah Jaw...

In [15]:
dataset_search_gb3 = dataset_search4.append(dataset_search_gb2)

In [16]:
dataset_search_gb3

                                               Tweets
0   Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...
1   @hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...
2   Lembaga penyiaran bersepakat melaksanakan peng...
3   RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...
4   Per tanggal 20 Desember 2022 pada pukul 24.00 ...
..                                                ...
95  RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...
96  RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...
97  Hallo pemirsa setia tvOne! \nSegera lakukan sc...
98  Setelah pemerintah menghentikan siaran TV anal...
99  RT @detikinet: #Terpopuler Kementerian Komunik...

[396 rows x 1 columns]

In [17]:
dataset_search = dataset_search_gb3

In [18]:
def cleanTweets(text):
    text = re.sub('@[A-Za-z0-9_]+', '', text) #removes @mentions
    text = re.sub('#','',text) #removes hastag '#' symbol
    text = re.sub('RT :[\s]+','',text)
    text = re.sub('https?:\/\/\S+', '', text) 
    text = re.sub('\n',' ',text)
    return text

dataset_search['cleanedTweets'] = dataset_search['Tweets'].apply(cleanTweets) #apply cleanTweet function to the tweet

In [19]:
dataset_search

,Tweets,cleanedTweets
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","Mulai 20 Desember 2022 pukul 24.00 WIB, siaran..."
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶
2,Lembaga penyiaran bersepakat melaksanakan peng...,Lembaga penyiaran bersepakat melaksanakan peng...
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,HARI INI TV ANALOG DIMATIKAN DI 10 WILAYAH JAW...
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,Per tanggal 20 Desember 2022 pada pukul 24.00 ...
...,...,...
95,RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...,Hallo pemirsa setia tvOne! Segera lakukan sca...
96,RT @tvOneNews: Hallo pemirsa setia tvOne! \nSe...,Hallo pemirsa setia tvOne! Segera lakukan sca...
97,Hallo pemirsa setia tvOne! \nSegera lakukan sc...,Hallo pemirsa setia tvOne! Segera lakukan sca...
98,Setelah pemerintah menghentikan siaran TV anal...,Setelah pemerintah menghentikan siaran TV anal...
99,RT @detikinet: #Terpopuler Kementerian Komunik...,Terpopuler Kementerian Komunikasi dan Informat...

In [20]:
dataset_search.drop_duplicates(inplace=True)

In [21]:
dataset_search

,Tweets,cleanedTweets
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","Mulai 20 Desember 2022 pukul 24.00 WIB, siaran..."
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶
2,Lembaga penyiaran bersepakat melaksanakan peng...,Lembaga penyiaran bersepakat melaksanakan peng...
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,HARI INI TV ANALOG DIMATIKAN DI 10 WILAYAH JAW...
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,Per tanggal 20 Desember 2022 pada pukul 24.00 ...
...,...,...
89,@jokowi semoga dengan adanya peralihan saluran...,semoga dengan adanya peralihan saluran tv dig...
90,@masyogpam Iya harusnya kalo tvnya dah digital...,"Iya harusnya kalo tvnya dah digital ya, anten..."
93,@kemkominfo Imbau Warga Jawa Timur Segera Pasa...,Imbau Warga Jawa Timur Segera Pasang STB Jela...
94,Masyarakat Surabaya dan sekitarnya akan merasa...,Masyarakat Surabaya dan sekitarnya akan merasa...
98,Setelah pemerintah menghentikan siaran TV anal...,Setelah pemerintah menghentikan siaran TV anal...

In [22]:
dataset_search['cleanedTweets'] = dataset_search['cleanedTweets'].str.lower()

In [23]:
dataset_search

,Tweets,cleanedTweets
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","mulai 20 desember 2022 pukul 24.00 wib, siaran..."
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶
2,Lembaga penyiaran bersepakat melaksanakan peng...,lembaga penyiaran bersepakat melaksanakan peng...
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,hari ini tv analog dimatikan di 10 wilayah jaw...
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,per tanggal 20 desember 2022 pada pukul 24.00 ...
...,...,...
89,@jokowi semoga dengan adanya peralihan saluran...,semoga dengan adanya peralihan saluran tv dig...
90,@masyogpam Iya harusnya kalo tvnya dah digital...,"iya harusnya kalo tvnya dah digital ya, anten..."
93,@kemkominfo Imbau Warga Jawa Timur Segera Pasa...,imbau warga jawa timur segera pasang stb jela...
94,Masyarakat Surabaya dan sekitarnya akan merasa...,masyarakat surabaya dan sekitarnya akan merasa...
98,Setelah pemerintah menghentikan siaran TV anal...,setelah pemerintah menghentikan siaran tv anal...

In [24]:
import translators as ts

Using state Jakarta server backend.

In [25]:
dataset_search['Translated'] = dataset_search['cleanedTweets'].apply(lambda x: ts.google(x, from_language='id', to_language='en'))

In [26]:
dataset_search.head()

,Tweets,cleanedTweets,Translated
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","mulai 20 desember 2022 pukul 24.00 wib, siaran...","Starting December 2022 at 24.00 WIB, analog br..."
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶,‚Ä¶
2,Lembaga penyiaran bersepakat melaksanakan peng...,lembaga penyiaran bersepakat melaksanakan peng...,Broadcasting Institution agreed to carry out a...
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,hari ini tv analog dimatikan di 10 wilayah jaw...,Today analog TV is turned off in 10 regions of...
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,per tanggal 20 desember 2022 pada pukul 24.00 ...,"As of December 20, 2022 at 24.00 WIB, analog T..."

In [27]:
from textblob import TextBlob

#get subjectivity and polarity of tweets with a function
def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

#get polarity with a function
def getPolarity(text):
    return TextBlob(text).sentiment.polarity

dataset_search['Subjectivity'] = dataset_search['Translated'].apply(getSubjectivity)
dataset_search['Polarity'] = dataset_search['Translated'].apply(getPolarity)

In [28]:
dataset_search.head()

,Tweets,cleanedTweets,Translated,Subjectivity,Polarity
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","mulai 20 desember 2022 pukul 24.00 wib, siaran...","Starting December 2022 at 24.00 WIB, analog br...",0.05,0.0
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶,‚Ä¶,0.00,0.0
2,Lembaga penyiaran bersepakat melaksanakan peng...,lembaga penyiaran bersepakat melaksanakan peng...,Broadcasting Institution agreed to carry out a...,0.00,0.0
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,hari ini tv analog dimatikan di 10 wilayah jaw...,Today analog TV is turned off in 10 regions of...,0.00,0.0
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,per tanggal 20 desember 2022 pada pukul 24.00 ...,"As of December 20, 2022 at 24.00 WIB, analog T...",0.00,0.0

In [29]:
#create a function to check negative, neutral and positive analysis
def getAnalysis(score):
    if score<0:
        return '-1'
    elif score == 0:
        return '0'
    else:
        return '1'
    
dataset_search['Analysis'] = dataset_search['Polarity'].apply(getAnalysis)

In [30]:
dataset_search['Analysis'].value_counts()

1     136
0      79
-1     78
Name: Analysis, dtype: int64

In [31]:
dataset_search.head()

,Tweets,cleanedTweets,Translated,Subjectivity,Polarity,Analysis
0,"Mulai 20 Desember 2022 pukul 24.00 WIB, siaran...","mulai 20 desember 2022 pukul 24.00 wib, siaran...","Starting December 2022 at 24.00 WIB, analog br...",0.05,0.0,0
1,@hyang_wisnu @kemkominfo @jokowi @PlateJohnny ...,‚Ä¶,‚Ä¶,0.00,0.0,0
2,Lembaga penyiaran bersepakat melaksanakan peng...,lembaga penyiaran bersepakat melaksanakan peng...,Broadcasting Institution agreed to carry out a...,0.00,0.0,0
3,RT @hyang_wisnu: HARI INI TV ANALOG DIMATIKAN ...,hari ini tv analog dimatikan di 10 wilayah jaw...,Today analog TV is turned off in 10 regions of...,0.00,0.0,0
4,Per tanggal 20 Desember 2022 pada pukul 24.00 ...,per tanggal 20 desember 2022 pada pukul 24.00 ...,"As of December 20, 2022 at 24.00 WIB, analog T...",0.00,0.0,0

In [32]:
dataset_search.to_csv('Downloads/STB_baru.csv', index=False)